version: '3.7'

services:

  db:
    ports:
      - 3307:3306
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: graphql
      MYSQL_PASSWORD: graphql
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
    driver: local